### PR TITLE
Fix 17 migrations - hopefully

### PR DESCRIPTION
**Pull request by yakky**
This still is not the final solution for the swappable model, but still should be better implementation of the migrations.
Real solution will imply the use of swappable meta attribute, but being still undocumented it may be tricky to properly implement it

### CODE REVIEW

**Comment by yakky** [comment]
@jsma care to review this?

**Comment by yakky** [comment]
Ping @jsma would you review if this solution fixes the issues with Django 1.7?

**Comment by jsma** [comment]
Sorry, literally in the middle of launching a big project. Might be able to regroup this weekend.

**Comment by yakky** [comment]
Thanks!

**Comment by jsma** [comment]
Very belated reply but can confirm no issues so far after upgrading to the latest on develop branch.

**Pull request merged**
