### PR TITLE
Proposal for fixing issue #553

### PR DESCRIPTION
**Pull request by ppomedio**
Edited .po files and re-created .mo with PoEdit version 1.8.2 (3969)

### CODE REVIEW

**Comment by ppomedio** [comment]
In french, it says (for the « root » one):

capture d ecran 2015-07-07 a 15 09 31

but there's noting in it!

capture d ecran 2015-07-07 a 15 09 59

**Comment by stefanfoulis** [comment]
Thanks for the pull-request @ppomedio . I'll have to figure out how to handle your change with transifex (https://www.transifex.com/organization/stefanfoulis/dashboard/django-filer) before merging.

**Comment by ppomedio** [comment]
Hi,
i don't have an account on Transifex, but maybe there's an update possibility for the PO files as mentioned at the bottom of [this page](http://docs.transifex.com/tutorials/content/#transifex-tips) (when they say “Modified strings as treated as new strings and added to Transifex as well”)?

**Comment by yakky** [comment]
@ppomedio if you remove POs from this PR we can merge the template changes and push update POs to transifex so you can review translations for each language

**Comment by ppomedio** [comment]
So i have to remove POs from the PR, but do i need to also remove MOs? I'll made a new commit ASAP when i'm sure of what to do :) .

**Comment by yakky** [comment]
@ppomedio POs and MOs so we can regenerate the POs and sync them with transifex so that all the translators can work on it
Basically the PR should contain only code / template changes

**Comment by ppomedio** [comment]
All po and mo files are now removed from PR.

**Comment by yakky** [comment]
@ppomedio gfreat, thanks. I'll update transifex shortly

**Pull request merged**
