### PR TITLE
swap jQuery with $, as jQuery seems undefined

### PR DESCRIPTION
**Pull request by benzkji**
this works for me. if jQuery is used, I get a 

````
focal_point.js:80 Uncaught TypeError: undefined is not a function
````

### CODE REVIEW

**Comment by yakky** [comment]
Fixed by #546 , sorry I spot that one before :)

**Comment by benzkji** [comment]
argh. too late :/ glad  this works now. any timeframe for another release? dont like pip -e ... ;-)

**Comment by yakky** [comment]
A few hours

**Comment by benzkji** [comment]
thank you sir!

**Pull request closed without merging**
