### PR TITLE
Fix parameter warnings

### LINKED ISSUE #466: SyntaxWarning: FilerFileField can only be a ForeignKey to File; filer.File passed
Hello sir,thanks for design this app,I try to lay out in my computer,but it cause the errors,how can I fix it?
Thanks!

```
/Library/Python/2.7/site-packages/filer/fields/file.py:118: SyntaxWarning: FilerFileField can only be a ForeignKey to File; filer.File passed
  warnings.warn(msg, SyntaxWarning)

Operations to perform:
  Synchronize unmigrated apps: filer, suit_ckeditor, staticfiles, suit, messages, django_select2, django_extensions, suit_redactor, import_export
  Apply all migrations: sessions, admin, auth, reversion, contenttypes, main, easy_thumbnails
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  No migrations to apply.
/Library/Python/2.7/site-packages/filer/fields/multistorage_file.py:106: SyntaxWarning: MultiStorageFileField can handle only File objects;<function generate_filename_multistorage at 0x1038df9b0> passed
  "%s passed" % upload_to, SyntaxWarning)


```

### LINKED ISSUE #488: MultiStorageFileField can handle only File object
Getting this warning all of a sudden

```
filer/fields/multistorage_file.py:106: SyntaxWarning: MultiStorageFileField can handle only File objects;<function generate_filename_multistorage at 0x10288fde8> passed
  "%s passed" % upload_to, SyntaxWarning)
```

On top of the  "SyntaxWarning: FilerImageField can only be a ForeignKey to Image; filer.Image passed" warning which I think already has a fix.

This is using filer 0.98, django 1.7.2

### PR DESCRIPTION
**Pull request by yakky**
Fix #466 
Fix #488

### CODE REVIEW

**Comment by cho-is** [comment]
still getting those warnings

**Comment by yakky** [comment]
@cho-is are you using develop branch?

**Comment by cho-is** [comment]
@yakky using django-filer==0.9.9

**Comment by rus11** [comment]
also the problem

Django (1.8.2)
django-filer (0.9.9)
django-filter (0.10.0)
django-mptt (0.7.3)
django-polymorphic (0.7.1)
django-registration-redux (1.2)
django-suit (0.2.13)
djangorestframework (3.1.2)
easy-thumbnails (2.2)
gunicorn (19.3.0)
Markdown (2.6.2)
Pillow (2.8.1)
pip (7.0.1)
psycopg2 (2.6)
setuptools (16.0)
Unidecode (0.4.17)
wheel (0.24.0)

**Comment by cho-is** [comment]
is there anything I can do to avoid those warnings?

**Pull request merged**
