### PR TITLE
Django 1.9 Deprecations

### PR DESCRIPTION
**Pull request by mattbriancon**
Almost a complete dupe of https://github.com/stefanfoulis/django-filer/pull/580 but it hasn't moved in a month and is in need of a rebase so I moved everything and resubmitted. Logs are spewing 1.9 warnings so hopefully we can get this released quickly!

### CODE REVIEW

**Comment by mattbriancon** [comment]
Also covers #597.

**Comment by yakky** [comment]
LGTM
@stefanfoulis dropping Django 1.4 it's not really a big deal to me

**Comment by mattbriancon** [comment]
Friendly bump. Just don't want to let this sit. Thanks!

**Comment by andreagrandi** [comment]
@yakky Python world is so small :D I got this warning too while trying to fix this project https://github.com/raspberrywhite/raspberrywhite/pull/27 from @astagi :)
I will put a note and wait for the next release to fix this specific warning.

**Comment by mattbriancon** [comment]
@stefanfoulis going on two weeks now. Can we merge and release this?

**Pull request merged**
