### PR TITLE
fix AttributeError: 'FileAdmin' object has no attribute 'queryset',

### LINKED ISSUE #528: [django 1.8] AttributeError: 'FileAdmin' object has no attribute 'queryset'
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/src/django-filer/filer/admin/fileadmin.py", line 100, in delete_view
    obj = self.queryset(request).get(pk=unquote(object_id))
AttributeError: 'FileAdmin' object has no attribute 'queryset'
```

### PR DESCRIPTION
**Pull request by bashu**
close #528

### CODE REVIEW

**Comment by yakky** [comment]
I'd rather change the occurrencies of ``self.queryset`` to ``self.get_queryset`` whenever needed than aliasing ``get_queryset`` to ``queryset``

**Comment by bashu** [comment]
I will fix that too

**Comment by bashu** [comment]
done =)

**Comment by yakky** [comment]
A self.queryset change for https://github.com/stefanfoulis/django-filer/pull/529/files#diff-d3544abce35931d328cca703f8101d48R108 is missing and I'd use the DJANGO_1_5 variable (at https://github.com/stefanfoulis/django-filer/blob/develop/filer/utils/compatibility.py#L20) for the version check, so it will be easier to go through the code when removing support for older Django versions

**Pull request closed without merging**
