### PR TITLE
Always use RequestContext instead of just Context

### PR DESCRIPTION
**Pull request by j00bar**

### CODE REVIEW

**Comment by yakky** [comment]
Thanks @j00bar and @gavinwahl !

**Comment by rockymeza** [comment]
just curious, why use render_to_response when [render](https://docs.djangoproject.com/en/1.8/topics/http/shortcuts/#render) exists (and has existed since Django 1.3).

**Comment by yakky** [comment]
@rockymeza I guess because of historical reasons (filer predates Django 1.3 and nobody felt compelled to update it). A PR is very welcome to fix this :)

**Comment by rockymeza** [comment]
@yakky :smile: hehe ok, fair enough!

**Comment by yakky** [comment]
Opened a new issue to track the code cleanup, thanks @rockymeza for pointing this put

**Pull request merged**
