### PR TITLE
Updated get_admin_url_path to work with django 1.8 deprecation 

### PR DESCRIPTION
**Pull request by zmetcalf**
I ran across this issue when using this code with Django 1.8. I copied this solution: https://github.com/lukaszb/django-guardian/pull/287

Sorry, but I did not run tests yet. I was having an issue getting them to work. 

Please advise any changes.

### CODE REVIEW

**Comment by yakky** [comment]
@zmetcalf which issues you have in running tests?

**Comment by zmetcalf** [comment]
Installing the right dependency was the main issue, because it kept saying cms_helper was not available. Looks like Travis likes it anyway. 

I am not sure it is your project, but when I create a migration, there is an issue with a missing table/field when using Django 1.8. Right now I have not isolated the issue, but if you have seen anything like it yet, it would help to know which direction to head. Otherwise never mind for now.

**Comment by yakky** [comment]
Django 1.8 it's still a bit off.
This projects uses tox to run the tests; from the project root:

    pip install tox
    tox

That's all

**Comment by yakky** [comment]
Could you please move the django importo on top of the other django ones?

**Comment by zmetcalf** [comment]
Yep, I will revise the patch this evening. Do you mind if I move all the imports above the djangos but below future?

**Comment by yakky** [comment]
That'd perfect.
Migration to be fully compliant with upstream coding style it's on our roadmap, so it's definitely the right path

**Comment by zmetcalf** [comment]
@yakky, I updated the commit. Thank you!

**Comment by yakky** [comment]
Thanks @zmetcalf !

**Pull request merged**
